services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DynamicSearchBundle\Factory\PaginatorFactoryInterface: '@DynamicSearchBundle\Factory\PaginatorFactory'
    DynamicSearchBundle\Factory\PaginatorFactory:
        arguments:
            $paginatorClass: '%dynamic_search_default_paginator_class%'

    DynamicSearchBundle\Factory\ContextDefinitionFactoryInterface: '@DynamicSearchBundle\Factory\ContextDefinitionFactory'
    DynamicSearchBundle\Factory\ContextDefinitionFactory: ~
