monolog:
    channels: ['dynamic_search']
    handlers:

        console:
            type: console
            channels:
                type: exclusive
                elements: ['!dynamic_search']

        dynamic_search_stream_logging:
            type: rotating_file
            max_files: 1
            path: '%kernel.project_dir%/var/bundles/DynamicSearchBundle/dynamic_search.log'
            channels: ['dynamic_search']
            formatter: dynamic_search.log.formatter.stream.provider
